[package]
name = "ephemera_api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = {version = "0.8.8", features=["ws"]}
hyper = "1.8.1"
rand = "0.9.2"
tokio = { version = "1.49.0", features = ["full"] }
